app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/root/App
  command: bash -c "cd /root/App && swift package clean && swift build && swift test && ./.build/debug/App"
