app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/App
  command: bash -c "cd /App && swift package clean && swift build --build-path .build-ubuntu && swift test && ./.build/debug/Server"
