stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
    - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${CF_REGION_ID}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash

      # Create services for app
      cf create-service "Auto-Scaling" "free" "swift-evolution-auto-scaling"

      # Get route for app
      # urls: swift-evolution-backend-mispublished-halituosity.mybluemix.net, data.swift-evolution.io, www.swift-evolution.io, swift-evolution.mybluemix.net, swift-evolution.io
      get_route() {
        APP_NAME=$1
        #url=$(cf app $APP_NAME | grep routes:)
        #url=${url#routes: }
        url=$(cf app $APP_NAME | grep urls:)
        url=${url#urls: }
        url=${url//[[:blank:]]/}
        route=${url%.mybluemix.net}
        echo $route
      }

      # Provision application
      if ! cf app $CF_APP; then
        cf push $CF_APP
      else
        # Push new version of the app
        CF_APP_TMP="${CF_APP}_tmp"
        cf push $CF_APP_TMP --random-route

        # Get route for currently running app
        tmp_route=$(get_route $CF_APP_TMP)
        echo "Temporary route: $tmp_route"
        route=$(get_route $CF_APP)
        echo "Original route: $route"

        # Update routes
        if [[ ! -z $route ]]; then
          cf map-route $CF_APP_TMP mybluemix.net --hostname $route
          cf unmap-route $CF_APP mybluemix.net --hostname $route
        fi
        if [[ ! -z $tmp_route ]]; then
          cf unmap-route $CF_APP_TMP mybluemix.net --hostname $tmp_route
        fi

        # Deprovision old version of app
        cf delete -f -r $CF_APP

        # Rename tmp app
        cf rename $CF_APP_TMP $CF_APP
      fi
